//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace micropay_apis.equiweb.apis {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ChannelIntegratorSoap", Namespace="http://bankequiweb.com/")]
    public partial class ChannelIntegrator : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback processServiceRequestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ChannelIntegrator() {
            this.Url = global::micropay_apis.Properties.Settings.Default.micropay_apis_equiweb_apis_ChannelIntegrator;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event processServiceRequestCompletedEventHandler processServiceRequestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bankequiweb.com/processServiceRequest", RequestNamespace="http://bankequiweb.com/", ResponseNamespace="http://bankequiweb.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceResponseWrapper processServiceRequest(ServiceRequestWrapper request) {
            object[] results = this.Invoke("processServiceRequest", new object[] {
                        request});
            return ((ServiceResponseWrapper)(results[0]));
        }
        
        /// <remarks/>
        public void processServiceRequestAsync(ServiceRequestWrapper request) {
            this.processServiceRequestAsync(request, null);
        }
        
        /// <remarks/>
        public void processServiceRequestAsync(ServiceRequestWrapper request, object userState) {
            if ((this.processServiceRequestOperationCompleted == null)) {
                this.processServiceRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocessServiceRequestOperationCompleted);
            }
            this.InvokeAsync("processServiceRequest", new object[] {
                        request}, this.processServiceRequestOperationCompleted, userState);
        }
        
        private void OnprocessServiceRequestOperationCompleted(object arg) {
            if ((this.processServiceRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.processServiceRequestCompleted(this, new processServiceRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankequiweb.com/")]
    public partial class ServiceRequestWrapper {
        
        private AuthenticationWrapper authRequestField;
        
        private ServiceRequestBody requestBodyField;
        
        /// <remarks/>
        public AuthenticationWrapper authRequest {
            get {
                return this.authRequestField;
            }
            set {
                this.authRequestField = value;
            }
        }
        
        /// <remarks/>
        public ServiceRequestBody requestBody {
            get {
                return this.requestBodyField;
            }
            set {
                this.requestBodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankequiweb.com/")]
    public partial class AuthenticationWrapper {
        
        private string channelCodeField;
        
        private string requestDigestField;
        
        private int institutionIdField;
        
        private string vCodeField;
        
        private string vPasswordField;
        
        private string phoneNumberField;
        
        private string pinField;
        
        private string userNameField;
        
        /// <remarks/>
        public string channelCode {
            get {
                return this.channelCodeField;
            }
            set {
                this.channelCodeField = value;
            }
        }
        
        /// <remarks/>
        public string requestDigest {
            get {
                return this.requestDigestField;
            }
            set {
                this.requestDigestField = value;
            }
        }
        
        /// <remarks/>
        public int institutionId {
            get {
                return this.institutionIdField;
            }
            set {
                this.institutionIdField = value;
            }
        }
        
        /// <remarks/>
        public string vCode {
            get {
                return this.vCodeField;
            }
            set {
                this.vCodeField = value;
            }
        }
        
        /// <remarks/>
        public string vPassword {
            get {
                return this.vPasswordField;
            }
            set {
                this.vPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string pin {
            get {
                return this.pinField;
            }
            set {
                this.pinField = value;
            }
        }
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankequiweb.com/")]
    public partial class StatementOutput {
        
        private string descriptionField;
        
        private string transDateField;
        
        private double transAmountField;
        
        private double closingBalanceField;
        
        private string debitCreditField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string transDate {
            get {
                return this.transDateField;
            }
            set {
                this.transDateField = value;
            }
        }
        
        /// <remarks/>
        public double transAmount {
            get {
                return this.transAmountField;
            }
            set {
                this.transAmountField = value;
            }
        }
        
        /// <remarks/>
        public double closingBalance {
            get {
                return this.closingBalanceField;
            }
            set {
                this.closingBalanceField = value;
            }
        }
        
        /// <remarks/>
        public string debitCredit {
            get {
                return this.debitCreditField;
            }
            set {
                this.debitCreditField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankequiweb.com/")]
    public partial class OutputItems {
        
        private Item[] exportItemsField;
        
        /// <remarks/>
        public Item[] exportItems {
            get {
                return this.exportItemsField;
            }
            set {
                this.exportItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankequiweb.com/")]
    public partial class Item {
        
        private string codeField;
        
        private string valueField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankequiweb.com/")]
    public partial class RequestOutput {
        
        private OutputItems outputParametersField;
        
        private StatementOutput[] transOutputField;
        
        private OutputItems[] outputParameterItemsField;
        
        /// <remarks/>
        public OutputItems outputParameters {
            get {
                return this.outputParametersField;
            }
            set {
                this.outputParametersField = value;
            }
        }
        
        /// <remarks/>
        public StatementOutput[] transOutput {
            get {
                return this.transOutputField;
            }
            set {
                this.transOutputField = value;
            }
        }
        
        /// <remarks/>
        public OutputItems[] outputParameterItems {
            get {
                return this.outputParameterItemsField;
            }
            set {
                this.outputParameterItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankequiweb.com/")]
    public partial class ServiceResponseWrapper {
        
        private string responseCodeField;
        
        private string responseMessageField;
        
        private RequestOutput requestOutputField;
        
        /// <remarks/>
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string responseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                this.responseMessageField = value;
            }
        }
        
        /// <remarks/>
        public RequestOutput requestOutput {
            get {
                return this.requestOutputField;
            }
            set {
                this.requestOutputField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankequiweb.com/")]
    public partial class InputItem {
        
        private Item[] itemsField;
        
        /// <remarks/>
        public Item[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankequiweb.com/")]
    public partial class RequestInput {
        
        private InputItem inputItemsField;
        
        /// <remarks/>
        public InputItem inputItems {
            get {
                return this.inputItemsField;
            }
            set {
                this.inputItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bankequiweb.com/")]
    public partial class ServiceRequestBody {
        
        private string serviceCodeField;
        
        private double requestIdField;
        
        private RequestInput requestInputField;
        
        /// <remarks/>
        public string serviceCode {
            get {
                return this.serviceCodeField;
            }
            set {
                this.serviceCodeField = value;
            }
        }
        
        /// <remarks/>
        public double requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        public RequestInput requestInput {
            get {
                return this.requestInputField;
            }
            set {
                this.requestInputField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void processServiceRequestCompletedEventHandler(object sender, processServiceRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class processServiceRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal processServiceRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceResponseWrapper Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceResponseWrapper)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591